### ISSUE TITLE
possible to host the blog via github pages?

### ISSUE THREAD

**Issue by xu4wang** [Benbinbin/BlogiNote-Starter-Template#1]
Thanks for the hard work, it looks great!

Noticed nuxt & content can generate a static website, I'm wondering if I can host my blog via github pages?

**Comment by Benbinbin** [comment]
Yep, with Github Action I think it's possible to deploy at Github Page. But I like to use Vercel, it's so easy to use just clicking some buttons and take the advantage of their free CDN service.
